name: pr-workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pr branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.sha }}

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run build script
        run: |
          cd deployment
          MI_STACK_NAME="pr${SHORT_SHA}"
          REGION=us-west-2
          VERSION="pr${SHORT_SHA}"
          DIST_OUTPUT_BUCKET=mie-dev
          TEMPLATE_OUTPUT_BUCKET=mie-dev-us-west-2
          echo y | ./build-s3-dist.sh --no-layer --template-bucket $TEMPLATE_OUTPUT_BUCKET --code-bucket $DIST_OUTPUT_BUCKET --version $VERSION --region $REGION
          read -r TEMPLATE < templateUrl.txt
          aws cloudformation deploy --stack-name $MI_STACK_NAME --region $REGION --template-file global-s3-assets/media-insights-on-aws-stack.template --s3-bucket $DIST_OUTPUT_BUCKET-$REGION --s3-prefix media-insights-on-aws/$VERSION --parameter-overrides DeployTestResources=Yes MaxConcurrentWorkflows=10 DeployAnalyticsPipeline=Yes EnableXrayTrace=Yes ParameterKey=SendAnonymousData,ParameterValue=false --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --force-upload
  test-us-west-2:
    needs: build-us-west-2
    runs-on: ubuntu-latest
    env:
      REGION: 'us-west-2'
    steps:
      - name: Check out pr branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.sha }}

      - name: Initialize test AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
            aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Generate short sha
        run: |
          echo "MI_STACK_NAME=pr`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Run cfn_nag
        uses: stelligent/cfn_nag@master
        continue-on-error: true
        with:
            input_path: deployment

      - name: Run unit tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/unit
          ./run_unit.sh
      - name: Run integ tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/integ
          ./run_integ.sh
      - name: Initialize build AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Delete stack
        run: |
          aws cloudformation delete-stack --stack-name $MI_STACK_NAME
