name: scheduled-solution-workflow

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  deploy-us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master branch
        uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run build script
        run: |
          cd deployment
          MIE_STACK_NAME=miesol
          REGION=us-west-2
          TEMPLATE=https://solutions-reference.s3.amazonaws.com/aws-media-insights-engine/latest/media-insights-stack.template
          aws cloudformation create-stack --stack-name $MIE_STACK_NAME --template-url $TEMPLATE --region $REGION --parameters ParameterKey=DeployTestResources,ParameterValue=true ParameterKey=EnableXrayTrace,ParameterValue=true ParameterKey=MaxConcurrentWorkflows,ParameterValue=10 ParameterKey=DeployAnalyticsPipeline,ParameterValue=true --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --profile default --disable-rollback
          aws cloudformation wait stack-create-complete --stack-name $MIE_STACK_NAME
      - name: Deploy Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly test for MIE solution failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ianwow
          labels: bug
          body: Nightly test failed for latest MIE solution

  test-us-west-2:
    needs: deploy-us-west-2
    runs-on: ubuntu-latest
    env:
      MIE_REGION: 'us-west-2'
      MIE_STACK_NAME: miesol
    steps:
      - name: Check out master branch
        uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run integ tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/integ
          ./run_integ.sh

      - name: Run E2E tests
        run: |
          cd $GITHUB_WORKSPACE
          cd test/e2e
          ./run_e2e.sh

      - name: Test Failed
        if: ${{ failure() }}
        uses: nashmaniac/create-issue-action@v1.1
        with:
          title: Nightly test for MIE solution failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ianwow
          labels: bug
          body: Nightly test failed for latest MIE solution
